### ISSUE TITLE
error 500 al cargar odoo por primera vez en el navegador

### ISSUE THREAD

**Issue by setterlee** [bmya/odoo-docker-scripts#3]
despues de ejecutar los scripts de instalacion y doeall, odoo no carga, anexo log:

`
`2017-06-28 21:37:58,453 1 INFO ? werkzeug: 172.17.0.5 - - [28/Jun/2017 21:37:58] "GET / HTTP/1.0" 500 -
2017-06-28 21:37:58,468 1 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 291, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1291, in __call__
    self.load_addons()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1301, in load_addons
    for module in sorted(os.listdir(str(addons_path))):
OSError: [Errno 2] No such file or directory: '/opt/odoo/stable-addons/oca/connector'
``

**Comment by Danisan** [comment]
Depende de la versión. Para hacer un debug, ejecuta lo siguiente para ingresar al contenedor:

      docker exec -ti odoo bash

Una vez dentro, fíjate si "/opt/odoo/stable-addons/oca/connector" existe. Si no existe, puede ser el openerp-server.conf, que esté con otra versión a la del contenedor, y buscando en el addons_path esa vía de acceso.

Bastará con ajustar openerp-server.conf para contener la vía correcta, o excluir la que no corresponde.

Para ésto, deberás tener mapeado el openerp-server.conf (u odoo.conf según el caso) con la siguiente linea en el archivo doeall:

-v /opt/odoo/conf:/etc/odoo

En el caso que no tengas el archivo openerp-server.conf en /opt/odoo/conf puedes extraerlo del docker así:

docker cp odoo:/etc/odoo/openerp-server.conf /opt/odoo/conf/

Espero cualquier comentario.

**Comment by Danisan** [comment]
Se quitó del addons_path los módulos que probablemente no estén disponibles en algunas versiones de construcción de docker
